In [1]:
import tensorflow as tf

a = tf.constant([5], dtype = tf.float32)
b = tf.constant([10], dtype = tf.float32)
c = tf.constant([2], dtype = tf.float32)

d = a * b + c

sess = tf.Session()
result = sess.run(d)
print result

[ 52.]


In [4]:
input_data = [1, 2, 3, 4, 5]
x = tf.placeholder(dtype=tf.float32)
y = x * 2

sess = tf.Session()
result = sess.run(y, feed_dict = {x : input_data})
print result

[  2.   4.   6.   8.  10.]


In [7]:
input_data = [1, 2, 3, 4, 5]
x = tf.placeholder(dtype = tf.float32)
W = tf.Variable([2], dtype = tf.float32)
y = W * x

sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
result = sess.run(y, feed_dict = {x : input_data})

print result

[  2.   4.   6.   8.  10.]


In [9]:
#matrix

x = tf.constant([[1.0, 2.0, 3.0]])
w = tf.constant([[2.0], [2.0], [2.0]])
y = tf.matmul(x, w)
print x.get_shape()

sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
result = sess.run(y)

print result

(1, 3)
[[ 12.]]


In [14]:
input_data = [[1, 1, 1], [2, 2, 2]]
x = tf.placeholder(dtype = tf.float32, shape = [2, 3])
w = tf.Variable([[2], [2], [2]], dtype = tf.float32)
b = tf.Variable([4], dtype = tf.float32)
y = tf.matmul(x, w) + b

sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
result = sess.run(y, feed_dict = {x : input_data})

print result

[[ 10.]
 [ 16.]]
